services:
  app:
    build:
      context: ./docker
    container_name: desafio-node-app
    restart: always
    volumes:
      - .:/home/app
    networks:
        - desafio-node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: desafio-node-db
    restart: always
    platform: linux/amd64
    volumes:
        - "mysql:/var/lib/mysql"
        -  ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    networks:
        - desafio-node-network
    environment:
      MYSQL_DATABASE: desafio_node
      MYSQL_ROOT_PASSWORD: desafio_node

  ngnix:
    image: nginx:alpine
    container_name: desafio-node-proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
        - desafio-node-network
    depends_on:
      - app

networks:
    desafio-node-network:
        driver: bridge

volumes:
    mysql:
      driver: local
